/**
 * Curated Tech Market Job Directory
 * Represents rich, real-world tech job opportunities across AI/ML, Full Stack,
 * Frontend, Backend, Cloud/DevOps, and Data Engineering.
 */

export const JOB_DIRECTORY = [
  // --- AI / ML Engineering ---
  {
    id: "job-oai-01",
    title: "AI Applied Research Engineer",
    company: "OpenAI",
    logoColor: "bg-emerald-700",
    roleCategory: "AI / ML Engineer",
    location: "San Francisco, CA",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "$195,000 - $280,000",
    salaryMin: 195000,
    salaryMax: 280000,
    postedDaysAgo: 1,
    requiredSkills: ["Python", "PyTorch", "LLM", "Prompt Engineering", "API Design", "TypeScript"],
    preferredSkills: ["RLHF", "LangChain", "Vector Databases", "Distributed Training", "Next.js"],
    description: "Join OpenAI's applied engineering team to build developer-facing APIs, fine-tuning infrastructure, and agent workflows powering next-generation generative AI products.",
    highlights: [
      "Work directly with GPT frontier models and inference optimization",
      "Scale developer tooling handling billions of token requests daily",
      "Competitive equity package + full healthcare + 401(k) matching",
    ],
    applyUrl: "https://job-boards.greenhouse.io/openai/jobs/5277884004",
    demoUrl: "/demo-application",
  },
  {
    id: "job-ant-02",
    title: "Full Stack AI Engineer",
    company: "Anthropic",
    logoColor: "bg-amber-700",
    roleCategory: "AI / ML Engineer",
    location: "San Francisco, CA / Remote (US)",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "$210,000 - $310,000",
    salaryMin: 210000,
    salaryMax: 310000,
    postedDaysAgo: 2,
    requiredSkills: ["TypeScript", "React", "Python", "Next.js", "Claude API", "TailwindCSS"],
    preferredSkills: ["FastAPI", "PostgreSQL", "Prompt Caching", "Docker", "AWS"],
    description: "Build interactive user experiences, web tooling, and evaluation harnesses around Claude 3.5 Sonnet and future frontier models with high reliability and safety standards.",
    highlights: [
      "Shape how millions of developers and enterprise users interact with Claude",
      "Autonomous product ownership with rapid release cycles",
      "Comprehensive remote stipend and top-tier benefits",
    ],
    applyUrl: "https://job-boards.greenhouse.io/anthropic/jobs/4019445007",
    demoUrl: "/demo-application",
  },
  {
    id: "job-sca-03",
    title: "Machine Learning Platform Engineer",
    company: "Scale AI",
    logoColor: "bg-purple-700",
    roleCategory: "AI / ML Engineer",
    location: "New York, NY",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "$165,000 - $225,000",
    salaryMin: 165000,
    salaryMax: 225000,
    postedDaysAgo: 3,
    requiredSkills: ["Python", "Kubernetes", "Docker", "PostgreSQL", "MLOps", "FastAPI"],
    preferredSkills: ["Ray", "PyTorch", "Redis", "Kafka", "GCP"],
    description: "Build robust distributed data ingestion pipelines, model fine-tuning jobs, and reinforcement learning evaluation infrastructure at Scale AI.",
    highlights: [
      "Power training data infrastructure for premier frontier AI labs",
      "Work on high-throughput distributed systems in production",
    ],
    applyUrl: "https://job-boards.greenhouse.io/scaleai/jobs/4329241004",
    demoUrl: "/demo-application",
  },
  {
    id: "job-per-04",
    title: "AI Systems & Inference Engineer",
    company: "Perplexity AI",
    logoColor: "bg-teal-700",
    roleCategory: "AI / ML Engineer",
    location: "San Francisco, CA / Remote",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "$190,000 - $270,000",
    salaryMin: 190000,
    salaryMax: 270000,
    postedDaysAgo: 2,
    requiredSkills: ["Python", "C++", "CUDA", "TensorRT", "FastAPI", "Vector Search"],
    preferredSkills: ["Triton", "PyTorch", "vLLM", "Distributed Systems"],
    description: "Help scale Perplexity's conversational search engine by optimizing real-time search indexing, embeddings retrieval, and low-latency LLM inference.",
    highlights: [
      "Direct impact on millions of daily active search queries",
      "Work with bleeding edge LLM serving engines and custom CUDA kernels",
    ],
    applyUrl: "https://jobs.ashbyhq.com/perplexity/48e91404-5853-4f51-b847-bb7cb1d76378",
    demoUrl: "/demo-application",
  },

  // --- Full Stack Engineering ---
  {
    id: "job-str-05",
    title: "Senior Full Stack Engineer, Developer Platform",
    company: "Stripe",
    logoColor: "bg-indigo-600",
    roleCategory: "Full Stack Engineer",
    location: "Remote (US/Canada)",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "$185,000 - $265,000",
    salaryMin: 185000,
    salaryMax: 265000,
    postedDaysAgo: 1,
    requiredSkills: ["JavaScript", "TypeScript", "React", "Node.js", "API Design", "PostgreSQL"],
    preferredSkills: ["Ruby", "GraphQL", "Microservices", "Next.js", "Redis"],
    description: "Build developer surfaces, dashboard experiences, and scalable APIs that process millions of transactions across the globe for Stripe's payments infrastructure.",
    highlights: [
      "Industry gold standard engineering culture and tooling",
      "100% remote-first team with flexible working hours",
      "Exceptional equity grants and annual performance bonuses",
    ],
    applyUrl: "https://job-boards.greenhouse.io/stripe/jobs/5829103002",
    demoUrl: "/demo-application",
  },
  {
    id: "job-lin-06",
    title: "Product Engineer (Full Stack)",
    company: "Linear",
    logoColor: "bg-blue-600",
    roleCategory: "Full Stack Engineer",
    location: "Remote (Global)",
    workplaceType: "Remote",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "$170,000 - $240,000",
    salaryMin: 170000,
    salaryMax: 240000,
    postedDaysAgo: 3,
    requiredSkills: ["TypeScript", "React", "Node.js", "WebSockets", "CSS", "UI/UX Design"],
    preferredSkills: ["PostgreSQL", "IndexedDB", "GraphQL", "TailwindCSS", "Performance Optimization"],
    description: "Craft high-performance, keyboard-first issue tracking software loved by top engineering organizations worldwide. Heavy emphasis on UI smoothness and snappy state sync.",
    highlights: [
      "World-class product design and ultra-fast client sync architecture",
      "Work with zero bureaucracy in a tight-knit high-talent crew",
      "Top-of-market base salary + equity",
    ],
    applyUrl: "https://jobs.ashbyhq.com/linear/1ccbe0ae-ba8d-4eb4-b976-59bfe00cbe90",
    demoUrl: "/demo-application",
  },
  {
    id: "job-ver-07",
    title: "Full Stack Engineer, Next.js & Cloud",
    company: "Vercel",
    logoColor: "bg-slate-900",
    roleCategory: "Full Stack Engineer",
    location: "Remote",
    workplaceType: "Remote",
    experienceLevel: "Mid-Level",
    salaryRange: "$160,000 - $220,000",
    salaryMin: 160000,
    salaryMax: 220000,
    postedDaysAgo: 4,
    requiredSkills: ["Next.js", "React", "TypeScript", "Node.js", "Server Components", "TailwindCSS"],
    preferredSkills: ["Edge Functions", "Turbopack", "PostgreSQL", "Vercel AI SDK", "Docker"],
    description: "Help build the web platform used by millions of developers. Work on Next.js runtime integration, server action ergonomics, and Vercel dashboard features.",
    highlights: [
      "Direct influence over modern web development standards",
      "Generous equipment and wellness stipend",
    ],
    applyUrl: "https://job-boards.greenhouse.io/vercel/jobs/5645391",
    demoUrl: "/demo-application",
  },
  {
    id: "job-sup-08",
    title: "Full Stack Platform Engineer",
    company: "Supabase",
    logoColor: "bg-emerald-600",
    roleCategory: "Full Stack Engineer",
    location: "Remote (Global)",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "$165,000 - $230,000",
    salaryMin: 165000,
    salaryMax: 230000,
    postedDaysAgo: 5,
    requiredSkills: ["TypeScript", "React", "PostgreSQL", "Node.js", "Docker", "REST API"],
    preferredSkills: ["Go", "Elixir", "Supabase Auth", "Next.js", "GraphQL"],
    description: "Build open source cloud tooling for developers. Work on database dashboards, real-time sync, auth integrations, and edge functions management.",
    highlights: [
      "100% remote asynchronous team across 30+ countries",
      "Build open source software used by 1M+ developers",
    ],
    applyUrl: "https://jobs.ashbyhq.com/supabase/305e9112-a5f7-4ebc-8857-7bbfaecb9ae9",
    demoUrl: "/demo-application",
  },

  // --- Frontend Engineer ---
  {
    id: "job-air-09",
    title: "Senior Frontend Engineer, Guest Experiences",
    company: "Airbnb",
    logoColor: "bg-rose-600",
    roleCategory: "Frontend Engineer",
    location: "San Francisco, CA / Remote",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "$175,000 - $250,000",
    salaryMin: 175000,
    salaryMax: 250000,
    postedDaysAgo: 2,
    requiredSkills: ["React", "TypeScript", "HTML5", "CSS", "Design Systems", "Web Performance"],
    preferredSkills: ["Next.js", "Accessibility (a11y)", "GraphQL", "Jest", "TailwindCSS"],
    description: "Design and implement world-class responsive web applications for millions of travelers. Champion accessible design, smooth micro-animations, and fast page loads.",
    highlights: [
      "Live and work anywhere program (travel stipends provided)",
      "Work with one of the most respected design system teams in tech",
    ],
    applyUrl: "https://careers.airbnb.com/positions/5640231/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-ret-10",
    title: "Frontend Systems Engineer",
    company: "Retool",
    logoColor: "bg-sky-600",
    roleCategory: "Frontend Engineer",
    location: "San Francisco, CA / New York, NY",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "$165,000 - $235,000",
    salaryMin: 165000,
    salaryMax: 235000,
    postedDaysAgo: 4,
    requiredSkills: ["TypeScript", "React", "JavaScript", "State Management", "DOM Performance"],
    preferredSkills: ["Canvas", "Web Workers", "Node.js", "PostgreSQL", "Cypress"],
    description: "Build Retool's core drag-and-drop IDE canvas, custom component runtime, and rich layout engine used by Fortune 500 companies to build internal tools.",
    highlights: [
      "Complex client-side architecture solving hard browser performance problems",
      "Fast-growing B2B product with huge developer traction",
    ],
    applyUrl: "https://job-boards.greenhouse.io/retool/jobs/5823194",
    demoUrl: "/demo-application",
  },
  {
    id: "job-fig-11",
    title: "Software Engineer, Web Platform & UI",
    company: "Figma",
    logoColor: "bg-violet-600",
    roleCategory: "Frontend Engineer",
    location: "San Francisco, CA / Remote",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "$180,000 - $260,000",
    salaryMin: 180000,
    salaryMax: 260000,
    postedDaysAgo: 1,
    requiredSkills: ["TypeScript", "React", "WebGL", "CSS", "WebAssembly", "Data Structures"],
    preferredSkills: ["C++", "Rust", "Design Systems", "Performance Profiling"],
    description: "Work on Figma's web application surface, multiplayer real-time collaboration canvas, and developer inspection modes.",
    highlights: [
      "Push browser capabilities to the absolute limit",
      "Unmatched collaborative design culture and strong perks",
    ],
    applyUrl: "https://job-boards.greenhouse.io/figma/jobs/5918231",
    demoUrl: "/demo-application",
  },

  // --- Backend / Distributed Systems ---
  {
    id: "job-ube-12",
    title: "Senior Backend Engineer, Core Logistics",
    company: "Uber",
    logoColor: "bg-black",
    roleCategory: "Backend Engineer",
    location: "Sunnyvale, CA / Seattle, WA",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "$180,000 - $260,000",
    salaryMin: 180000,
    salaryMax: 260000,
    postedDaysAgo: 3,
    requiredSkills: ["Go", "Java", "PostgreSQL", "Kafka", "Microservices", "System Design"],
    preferredSkills: ["Redis", "gRPC", "Docker", "Kubernetes", "Cassandra"],
    description: "Architect high-throughput real-time matching, dispatch, and routing algorithms serving tens of millions of rides and deliveries every single day.",
    highlights: [
      "Petabyte-scale distributed systems and high-availability operations",
      "Generous RSU refreshers and competitive annual bonus",
    ],
    applyUrl: "https://uber.wd5.myworkdayjobs.com/UberCareers/job/Software-Engineer-Backend_JR123456",
    demoUrl: "/demo-application",
  },
  {
    id: "job-cld-13",
    title: "Systems Engineer, Distributed Edge Storage",
    company: "Cloudflare",
    logoColor: "bg-orange-600",
    roleCategory: "Backend Engineer",
    location: "Austin, TX / Remote",
    workplaceType: "Remote",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "$160,000 - $230,000",
    salaryMin: 160000,
    salaryMax: 230000,
    postedDaysAgo: 5,
    requiredSkills: ["Rust", "Go", "Distributed Systems", "Linux", "Networking", "API Design"],
    preferredSkills: ["C++", "PostgreSQL", "Docker", "eBPF", "TypeScript"],
    description: "Design low-latency key-value storage, database replication, and edge computing primitives running across Cloudflare's 300+ city global network.",
    highlights: [
      "Help make the global internet faster and more secure",
      "Strong remote-friendly engineering culture",
    ],
    applyUrl: "https://job-boards.greenhouse.io/cloudflare/jobs/5839210",
    demoUrl: "/demo-application",
  },
  {
    id: "job-dat-14",
    title: "Backend Engineer, Observability Pipelines",
    company: "Datadog",
    logoColor: "bg-purple-800",
    roleCategory: "Backend Engineer",
    location: "New York, NY / Boston, MA",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "$155,000 - $215,000",
    salaryMin: 155000,
    salaryMax: 215000,
    postedDaysAgo: 2,
    requiredSkills: ["Python", "Go", "PostgreSQL", "Kafka", "Docker", "REST API"],
    preferredSkills: ["Kubernetes", "Redis", "Elasticsearch", "AWS", "Prometheus"],
    description: "Build telemetry processing engines that stream trillions of metrics, logs, and traces per day with sub-second query latency.",
    highlights: [
      "Fastest growing cloud observability platform",
      "Work with massive scale distributed databases and streaming pipelines",
    ],
    applyUrl: "https://job-boards.greenhouse.io/datadog/jobs/5719382",
    demoUrl: "/demo-application",
  },

  // --- DevOps / Cloud / Platform ---
  {
    id: "job-aws-15",
    title: "Cloud Infrastructure & Platform Engineer",
    company: "Amazon Web Services (AWS)",
    logoColor: "bg-amber-600",
    roleCategory: "DevOps / Cloud Engineer",
    location: "Seattle, WA / Arlington, VA",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "$170,000 - $250,000",
    salaryMin: 170000,
    salaryMax: 250000,
    postedDaysAgo: 4,
    requiredSkills: ["AWS", "Kubernetes", "Terraform", "Docker", "CI/CD", "Linux"],
    preferredSkills: ["Python", "Go", "Helm", "Prometheus", "Security / IAM"],
    description: "Build self-service container orchestration, multi-region failover, and infrastructure-as-code automation for Tier-1 cloud services.",
    highlights: [
      "Foundational infrastructure supporting the global internet economy",
      "Substantial total compensation and industry prestige",
    ],
    applyUrl: "https://amazon.jobs/en/jobs/2598341/software-development-engineer-aws",
    demoUrl: "/demo-application",
  },
  {
    id: "job-has-16",
    title: "DevOps & SRE Engineer",
    company: "HashiCorp",
    logoColor: "bg-slate-800",
    roleCategory: "DevOps / Cloud Engineer",
    location: "Remote (US/Canada)",
    workplaceType: "Remote",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "$160,000 - $225,000",
    salaryMin: 160000,
    salaryMax: 225000,
    postedDaysAgo: 3,
    requiredSkills: ["Terraform", "Kubernetes", "Go", "Docker", "Linux", "GCP/AWS"],
    preferredSkills: ["Vault", "Consul", "Python", "Observability", "Ansible"],
    description: "Manage and automate multi-cloud infrastructure, internal deployment pipelines, and zero-trust security perimeters using HashiCorp Cloud Platform.",
    highlights: [
      "Pioneer in Infrastructure as Code and cloud automation",
      "True remote-first culture with generous home office allowances",
    ],
    applyUrl: "https://job-boards.greenhouse.io/hashicorp/jobs/5632190",
    demoUrl: "/demo-application",
  },

  // --- Data Engineering / Analytics ---
  {
    id: "job-sno-17",
    title: "Senior Data Platform Engineer",
    company: "Snowflake",
    logoColor: "bg-cyan-600",
    roleCategory: "Data Engineer",
    location: "San Mateo, CA / Remote",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "$180,000 - $255,000",
    salaryMin: 180000,
    salaryMax: 255000,
    postedDaysAgo: 2,
    requiredSkills: ["SQL", "Python", "Snowflake", "Data Warehousing", "ETL", "Kafka"],
    preferredSkills: ["Spark", "dbt", "Airflow", "Docker", "AWS"],
    description: "Architect petabyte-scale data pipelines, real-time analytics streaming, and enterprise data governance infrastructure for Snowflake's cloud platform.",
    highlights: [
      "Work at the cutting edge of cloud data warehousing and data science",
      "Highly competitive compensation and RSU packages",
    ],
    applyUrl: "https://job-boards.greenhouse.io/snowflake/jobs/5812903",
    demoUrl: "/demo-application",
  },
  {
    id: "job-dbt-18",
    title: "Analytics & Data Integration Engineer",
    company: "dbt Labs",
    logoColor: "bg-orange-500",
    roleCategory: "Data Engineer",
    location: "Remote",
    workplaceType: "Remote",
    experienceLevel: "Mid-Level",
    salaryRange: "$150,000 - $205,000",
    salaryMin: 150000,
    salaryMax: 205000,
    postedDaysAgo: 6,
    requiredSkills: ["SQL", "Python", "dbt", "PostgreSQL", "Data Modeling", "Git"],
    preferredSkills: ["BigQuery", "Snowflake", "Airflow", "TypeScript", "CI/CD"],
    description: "Empower thousands of data teams to transform data in production. Build dbt Cloud plugins, semantic layer models, and data testing automations.",
    highlights: [
      "Creator of the open source standard for modern data transformation",
      "Transparent remote company culture and strong community",
    ],
    applyUrl: "https://job-boards.greenhouse.io/dbtlabsinc/jobs/5891234",
    demoUrl: "/demo-application",
  },

  // --- India Tech Opportunities ---
  {
    id: "job-atl-in-19",
    title: "Senior Full Stack Software Engineer",
    company: "Atlassian",
    logoColor: "bg-blue-700",
    roleCategory: "Full Stack Engineer",
    location: "Bengaluru, India / Remote (India)",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "₹38,00,000 - ₹55,00,000 / yr",
    salaryMin: 180000,
    salaryMax: 250000,
    postedDaysAgo: 1,
    requiredSkills: ["React", "TypeScript", "Node.js", "Java", "Microservices", "REST API"],
    preferredSkills: ["GraphQL", "AWS", "PostgreSQL", "Kafka", "Docker"],
    description: "Join Atlassian's core Jira and Confluence cloud engineering group in India. Build scalable micro-frontend architectures and distributed cloud microservices.",
    highlights: [
      "TEAM Anywhere policy: 100% remote working flexibility across India",
      "World-class R&D campus in Bengaluru with extensive learning benefits",
    ],
    applyUrl: "https://www.atlassian.com/company/careers/details/R-00000438",
    demoUrl: "/demo-application",
  },
  {
    id: "job-goog-in-20",
    title: "Senior Software Engineer - Google Cloud & Search Infra",
    company: "Google",
    logoColor: "bg-blue-600",
    roleCategory: "Backend Engineer",
    location: "Bengaluru / Hyderabad, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹48,00,000 - ₹72,00,000 / yr",
    salaryMin: 190000,
    salaryMax: 290000,
    postedDaysAgo: 1,
    requiredSkills: ["C++", "Java", "Go", "Distributed Systems", "Kubernetes", "gRPC"],
    preferredSkills: ["Borg", "Spanner", "Bigtable", "Linux Kernel", "Machine Learning"],
    description: "Build global-scale infrastructure, cloud storage engines, and search indexing systems supporting billions of queries daily at Google India R&D centers.",
    highlights: [
      "Work on critical distributed systems powering Google Cloud & Global Search",
      "Comprehensive healthcare, annual equity refreshers, and hybrid flexibility",
    ],
    applyUrl: "https://www.google.com/about/careers/applications/jobs/results/?location=India",
    demoUrl: "/demo-application",
  },
  {
    id: "job-msft-in-21",
    title: "Software Engineer II - Azure AI Platform",
    company: "Microsoft",
    logoColor: "bg-blue-600",
    roleCategory: "AI / ML Engineer",
    location: "Hyderabad / Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹32,00,000 - ₹48,00,000 / yr",
    salaryMin: 160000,
    salaryMax: 220000,
    postedDaysAgo: 2,
    requiredSkills: ["Python", "C#", "PyTorch", "Azure", "Distributed Systems", "REST API"],
    preferredSkills: ["LLM", "Docker", "Kubernetes", "C++", "FastAPI"],
    description: "Develop generative AI inference engines, model fine-tuning frameworks, and enterprise Copilot integration platforms at Microsoft IDC India.",
    highlights: [
      "Work directly on OpenAI integration and Azure AI infrastructure",
      "Comprehensive family health insurance and annual stock refreshers",
    ],
    applyUrl: "https://jobs.careers.microsoft.com/global/en/job/1769824",
    demoUrl: "/demo-application",
  },
  {
    id: "job-amzn-in-22",
    title: "Software Development Engineer II (SDE II) - AWS Infrastructure",
    company: "Amazon",
    logoColor: "bg-amber-600",
    roleCategory: "Backend Engineer",
    location: "Bengaluru / Hyderabad, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "₹36,00,000 - ₹54,00,000 / yr",
    salaryMin: 170000,
    salaryMax: 240000,
    postedDaysAgo: 2,
    requiredSkills: ["Java", "Distributed Systems", "AWS", "DynamoDB", "REST API", "CI/CD"],
    preferredSkills: ["Kotlin", "Lambda", "Docker", "Microservices", "Event-Driven Architecture"],
    description: "Architect high-availability AWS cloud control planes and retail high-throughput microservices handling millions of transactions per minute.",
    highlights: [
      "Direct ownership of tier-1 cloud services running at global hyper-scale",
      "Robust stock grant package and structured engineering growth tracks",
    ],
    applyUrl: "https://amazon.jobs/en/search?loc_query=India",
    demoUrl: "/demo-application",
  },
  {
    id: "job-flip-in-23",
    title: "Lead Software Engineer - Supply Chain & Logistics Tech",
    company: "Flipkart",
    logoColor: "bg-blue-600",
    roleCategory: "Backend Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹45,00,000 - ₹68,00,000 / yr",
    salaryMin: 180000,
    salaryMax: 260000,
    postedDaysAgo: 1,
    requiredSkills: ["Java", "Kafka", "MySQL", "Redis", "Distributed Systems", "Microservices"],
    preferredSkills: ["HBase", "Aerospike", "Spring Boot", "Docker", "Kubernetes"],
    description: "Lead architecture and engineering for Flipkart's core fulfilment and real-time inventory management engines powering India's largest e-commerce festivals.",
    highlights: [
      "Design systems capable of scaling to 100k+ requests per second during Big Billion Days",
      "Generous performance bonuses and Flipkart stock ownership programs",
    ],
    applyUrl: "https://www.flipkartcareers.com/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-swig-in-24",
    title: "Backend Platform Engineer, High Scale Logistics",
    company: "Swiggy",
    logoColor: "bg-orange-600",
    roleCategory: "Backend Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹40,00,000 - ₹60,00,000 / yr",
    salaryMin: 170000,
    salaryMax: 240000,
    postedDaysAgo: 3,
    requiredSkills: ["Go", "Java", "Kafka", "Redis", "PostgreSQL", "Distributed Systems"],
    preferredSkills: ["Kubernetes", "AWS", "gRPC", "Elasticsearch", "Cassandra"],
    description: "Architect high-throughput, low-latency dispatch and routing algorithms handling millions of daily on-demand delivery orders.",
    highlights: [
      "Ultra high-scale distributed architecture processing peak Indian traffic",
      "Fast-paced product engineering environment with generous equity",
    ],
    applyUrl: "https://careers.swiggy.com/#/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-rzp-in-25",
    title: "Staff Platform Engineer - Payment Gateway Core",
    company: "Razorpay",
    logoColor: "bg-blue-700",
    roleCategory: "Backend Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹50,00,000 - ₹75,00,000 / yr",
    salaryMin: 190000,
    salaryMax: 280000,
    postedDaysAgo: 1,
    requiredSkills: ["Go", "Node.js", "PostgreSQL", "Kafka", "Redis", "Microservices"],
    preferredSkills: ["AWS", "Docker", "Kubernetes", "Fintech API", "High Concurrency"],
    description: "Build ultra-reliable payment processing engines and instant settlement infrastructure handling over $100B+ annual total payment volume.",
    highlights: [
      "Direct impact on powering digital payments for 10M+ Indian businesses",
      "Top-tier fintech compensation with ESOP liquidity programs",
    ],
    applyUrl: "https://razorpay.com/jobs/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-php-in-26",
    title: "Senior Software Engineer - UPI Core & Merchant Platform",
    company: "PhonePe",
    logoColor: "bg-purple-700",
    roleCategory: "Backend Engineer",
    location: "Bengaluru / Pune, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹42,00,000 - ₹65,00,000 / yr",
    salaryMin: 175000,
    salaryMax: 250000,
    postedDaysAgo: 2,
    requiredSkills: ["Java", "Spring Boot", "Kafka", "HBase", "MySQL", "Distributed Caching"],
    preferredSkills: ["Aerospike", "Kubernetes", "gRPC", "Microservices", "Observability"],
    description: "Power India's largest UPI payments network processing over 45% of total national UPI volume with 99.999% uptime guarantees.",
    highlights: [
      "Architect sub-millisecond payment settlement pipelines at nationwide scale",
      "Generous stock options and comprehensive employee wellness perks",
    ],
    applyUrl: "https://www.phonepe.com/careers/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-crd-in-27",
    title: "Senior Backend / Systems Engineer - Financial Ledger",
    company: "CRED",
    logoColor: "bg-slate-900",
    roleCategory: "Backend Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹45,00,000 - ₹70,00,000 / yr",
    salaryMin: 180000,
    salaryMax: 270000,
    postedDaysAgo: 2,
    requiredSkills: ["Go", "Java", "PostgreSQL", "Kafka", "Redis", "Distributed Systems"],
    preferredSkills: ["Event Sourcing", "Docker", "Kubernetes", "AWS", "Financial Engines"],
    description: "Engineer immutable double-entry ledger platforms and high-speed reward verification engines for India's premier creditworthy community.",
    highlights: [
      "Work alongside world-class engineering talent with craft-first design culture",
      "Industry-leading equity packages and comprehensive family insurance",
    ],
    applyUrl: "https://jobs.lever.co/cred",
    demoUrl: "/demo-application",
  },
  {
    id: "job-post-in-28",
    title: "Senior Full Stack Platform Engineer - API Runtime",
    company: "Postman",
    logoColor: "bg-orange-600",
    roleCategory: "Full Stack Engineer",
    location: "Bengaluru, India / Remote (India)",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "₹38,00,000 - ₹58,00,000 / yr",
    salaryMin: 175000,
    salaryMax: 250000,
    postedDaysAgo: 3,
    requiredSkills: ["TypeScript", "Node.js", "React", "Next.js", "Electron", "REST API"],
    preferredSkills: ["GraphQL", "WebSockets", "Docker", "AWS", "API Specifications"],
    description: "Build features for the world's leading API platform used by over 30 million developers across 500,000 organizations worldwide.",
    highlights: [
      "100% remote working flexibility across India with home office setup stipends",
      "Direct impact on the global developer ecosystem and API standards",
    ],
    applyUrl: "https://www.postman.com/company/careers/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-zept-in-29",
    title: "Lead Backend Engineer - 10-Minute Dark Store Dispatch Engine",
    company: "Zepto",
    logoColor: "bg-purple-800",
    roleCategory: "Backend Engineer",
    location: "Bengaluru / Mumbai, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹42,00,000 - ₹65,00,000 / yr",
    salaryMin: 175000,
    salaryMax: 250000,
    postedDaysAgo: 2,
    requiredSkills: ["Go", "Node.js", "PostgreSQL", "Redis", "Kafka", "Microservices"],
    preferredSkills: ["Spatial Indexing", "Kubernetes", "AWS", "Elasticsearch", "FastAPI"],
    description: "Architect sub-second dark store picker routing, hyper-local inventory allocations, and rider batching algorithms for quick-commerce delivery.",
    highlights: [
      "High velocity, hyper-growth quick-commerce engineering environment",
      "Significant pre-IPO equity grants and aggressive career acceleration",
    ],
    applyUrl: "https://www.zeptonow.com/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-zom-in-30",
    title: "Senior Backend Engineer - Live Order Stream & Quick Commerce",
    company: "Zomato",
    logoColor: "bg-red-600",
    roleCategory: "Backend Engineer",
    location: "Gurgaon / Remote (India)",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹38,00,000 - ₹58,00,000 / yr",
    salaryMin: 170000,
    salaryMax: 245000,
    postedDaysAgo: 1,
    requiredSkills: ["Go", "Python", "Kafka", "MySQL", "Redis", "Distributed Systems"],
    preferredSkills: ["Kubernetes", "AWS", "gRPC", "Elasticsearch", "ClickHouse"],
    description: "Design live streaming event processing architectures, real-time rider tracking, and merchant catalog sync for millions of food and grocery orders.",
    highlights: [
      "Operate at peak national concurrency handling record festival demand",
      "Dynamic tech culture with high autonomy and attractive equity upside",
    ],
    applyUrl: "https://www.zomato.com/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-zero-in-31",
    title: "Systems & Backend Engineer - Kite Ultra-Low Latency Trading",
    company: "Zerodha",
    logoColor: "bg-blue-700",
    roleCategory: "Backend Engineer",
    location: "Bengaluru, India / Remote (India)",
    workplaceType: "Remote",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "₹24,00,000 - ₹40,00,000 / yr",
    salaryMin: 120000,
    salaryMax: 200000,
    postedDaysAgo: 2,
    requiredSkills: ["Go", "Python", "PostgreSQL", "Redis", "Linux", "WebSockets"],
    preferredSkills: ["C", "Rust", "Network Protocols", "Distributed Systems", "Nginx"],
    description: "Build robust, minimalist, ultra-low latency trading systems and market data streaming pipelines handling 15M+ active retail investors.",
    highlights: [
      "Remote-first engineering team renowned for clean, unbloated software craft",
      "Exceptional work-life balance and transparent compensation",
    ],
    applyUrl: "https://zerodha.com/careers",
    demoUrl: "/demo-application",
  },

  // --- Tier 2 & Tier 3 Tech Leaders, IT Services & Consultancies ---
  {
    id: "job-zoho-in-32",
    title: "Software Engineer - Enterprise Cloud Applications",
    company: "Zoho",
    logoColor: "bg-red-600",
    roleCategory: "Full Stack Engineer",
    location: "Chennai / Tenkasi / Salem, India",
    workplaceType: "Onsite",
    experienceLevel: "Entry-to-Mid",
    salaryRange: "₹6,50,000 - ₹12,00,000 / yr",
    salaryMin: 65000,
    salaryMax: 120000,
    postedDaysAgo: 2,
    requiredSkills: ["Java", "JavaScript", "C++", "MySQL", "HTML5", "CSS"],
    preferredSkills: ["React", "Linux", "Distributed Storage", "REST API"],
    description: "Design and develop enterprise SaaS applications, document editors, and CRM tooling serving over 100M+ global users from Zoho's rural and urban campuses.",
    highlights: [
      "Bootstrapped, highly profitable tech giant with zero investor pressure",
      "World-class product culture with extensive on-campus dining and amenities",
    ],
    applyUrl: "https://www.zoho.com/careers/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-fresh-in-33",
    title: "Product Software Engineer - Customer Experience Cloud",
    company: "Freshworks",
    logoColor: "bg-amber-600",
    roleCategory: "Backend Engineer",
    location: "Chennai / Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹14,00,000 - ₹24,00,000 / yr",
    salaryMin: 110000,
    salaryMax: 170000,
    postedDaysAgo: 1,
    requiredSkills: ["Ruby on Rails", "Java", "Node.js", "MySQL", "Redis", "AWS"],
    preferredSkills: ["Kafka", "Docker", "Kubernetes", "Ember.js", "Microservices"],
    description: "Build high-throughput customer support and IT service management microservices for Freshworks' NASDAQ-listed cloud platform.",
    highlights: [
      "Pioneer in Indian SaaS with international enterprise reach",
      "Generous health benefits, flexible working, and global mobility options",
    ],
    applyUrl: "https://www.freshworks.com/company/careers/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-tcs-in-34",
    title: "Systems Engineer - Cloud & Enterprise Microservices",
    company: "TCS",
    logoColor: "bg-blue-800",
    roleCategory: "Full Stack Engineer",
    location: "Hyderabad / Pune / Bengaluru / Chennai, India",
    workplaceType: "Hybrid",
    experienceLevel: "Entry-Level",
    salaryRange: "₹4,50,000 - ₹8,50,000 / yr",
    salaryMin: 45000,
    salaryMax: 85000,
    postedDaysAgo: 3,
    requiredSkills: ["Java", "Spring Boot", "SQL", "JavaScript", "HTML5", "Git"],
    preferredSkills: ["Angular", "React", "Azure", "AWS", "Docker"],
    description: "Develop enterprise software, modern cloud microservices, and digital transformation solutions for Global Fortune 500 clients.",
    highlights: [
      "India's largest IT company with extensive global project opportunities",
      "Structured learning paths via TCS Elevate and comprehensive medical cover",
    ],
    applyUrl: "https://www.tcs.com/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-infy-in-35",
    title: "Specialist Programmer - Digital Engineering",
    company: "Infosys",
    logoColor: "bg-blue-600",
    roleCategory: "Full Stack Engineer",
    location: "Bengaluru / Mysuru / Pune / Hyderabad, India",
    workplaceType: "Hybrid",
    experienceLevel: "Entry-to-Mid",
    salaryRange: "₹5,00,000 - ₹9,50,000 / yr",
    salaryMin: 50000,
    salaryMax: 95000,
    postedDaysAgo: 2,
    requiredSkills: ["Python", "Java", "React", "Node.js", "PostgreSQL", "REST API"],
    preferredSkills: ["Docker", "Kubernetes", "AWS", "CI/CD", "Spring Cloud"],
    description: "Build robust full-stack applications and cloud-native microservices within Infosys Cobalt digital engineering suites.",
    highlights: [
      "Premier Infosys Specialist Programmer track with fast-tracked career growth",
      "Iconic Mysuru and Electronic City Bengaluru campuses with world-class facilities",
    ],
    applyUrl: "https://www.infosys.com/careers.html",
    demoUrl: "/demo-application",
  },
  {
    id: "job-wipro-in-36",
    title: "Cloud & DevOps Engineer - Modern Infrastructure",
    company: "Wipro",
    logoColor: "bg-emerald-600",
    roleCategory: "DevOps / Cloud Engineer",
    location: "Bengaluru / Hyderabad / Pune, India",
    workplaceType: "Hybrid",
    experienceLevel: "Entry-to-Mid",
    salaryRange: "₹4,80,000 - ₹8,80,000 / yr",
    salaryMin: 48000,
    salaryMax: 88000,
    postedDaysAgo: 3,
    requiredSkills: ["Linux", "AWS", "Docker", "Terraform", "Python", "CI/CD"],
    preferredSkills: ["Kubernetes", "Ansible", "Jenkins", "Azure", "Shell Scripting"],
    description: "Automate continuous deployment pipelines, manage containerized clusters, and monitor hybrid cloud environments for global customers.",
    highlights: [
      "Hands-on experience deploying modern multi-cloud architectures",
      "Flexible working policies and industry certification sponsorship",
    ],
    applyUrl: "https://careers.wipro.com/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-ltim-in-37",
    title: "Full Stack Developer - Java & React Services",
    company: "LTIMindtree",
    logoColor: "bg-blue-700",
    roleCategory: "Full Stack Engineer",
    location: "Mumbai / Pune / Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹6,00,000 - ₹11,00,000 / yr",
    salaryMin: 60000,
    salaryMax: 110000,
    postedDaysAgo: 2,
    requiredSkills: ["Java", "Spring Boot", "React", "TypeScript", "MySQL", "REST API"],
    preferredSkills: ["Microservices", "Kafka", "AWS", "Docker", "GraphQL"],
    description: "Architect and implement digital banking and retail web platforms using micro-frontends and Spring Boot microservices.",
    highlights: [
      "Top-tier mid-market IT powerhouse with strong enterprise relationships",
      "Comprehensive employee rewards, health coverage, and upskilling allowances",
    ],
    applyUrl: "https://www.ltimindtree.com/careers/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-pers-in-38",
    title: "Software Engineer - Distributed Cloud Platforms",
    company: "Persistent Systems",
    logoColor: "bg-orange-600",
    roleCategory: "Backend Engineer",
    location: "Pune / Hyderabad / Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹7,50,000 - ₹13,50,000 / yr",
    salaryMin: 75000,
    salaryMax: 135000,
    postedDaysAgo: 1,
    requiredSkills: ["Java", "Python", "AWS", "PostgreSQL", "Kafka", "Docker"],
    preferredSkills: ["Kubernetes", "FastAPI", "Redis", "Spring Boot", "Microservices"],
    description: "Design high-performance cloud backends and software products for international healthcare and BFSI clients.",
    highlights: [
      "Product-centric engineering culture in Pune and Hyderabad IT corridors",
      "Fast-paced project rotations with cutting-edge tech stacks",
    ],
    applyUrl: "https://www.persistent.com/careers/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-hcl-in-39",
    title: "Cloud Native Backend Engineer",
    company: "HCLTech",
    logoColor: "bg-indigo-700",
    roleCategory: "Backend Engineer",
    location: "Noida / Chennai / Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Entry-to-Mid",
    salaryRange: "₹5,50,000 - ₹9,80,000 / yr",
    salaryMin: 55000,
    salaryMax: 98000,
    postedDaysAgo: 3,
    requiredSkills: ["Java", "Node.js", "MySQL", "AWS", "REST API", "Docker"],
    preferredSkills: ["Python", "Kubernetes", "GCP", "Microservices", "CI/CD"],
    description: "Build robust REST APIs and scalable backend services powering digital transformation across telecom and financial sectors.",
    highlights: [
      "Prominent global tech company headquartered in Noida",
      "Competitive benefits package and structured promotions",
    ],
    applyUrl: "https://www.hcltech.com/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-cog-in-40",
    title: "Full Stack Engineer - MERN & Cloud",
    company: "Cognizant",
    logoColor: "bg-blue-800",
    roleCategory: "Full Stack Engineer",
    location: "Chennai / Kolkata / Hyderabad / Pune, India",
    workplaceType: "Hybrid",
    experienceLevel: "Entry-to-Mid",
    salaryRange: "₹5,20,000 - ₹9,20,000 / yr",
    salaryMin: 52000,
    salaryMax: 92000,
    postedDaysAgo: 2,
    requiredSkills: ["React", "Node.js", "JavaScript", "MongoDB", "Express", "REST API"],
    preferredSkills: ["TypeScript", "Docker", "AWS", "Jest", "TailwindCSS"],
    description: "Develop full-stack web applications, customer portals, and integration middleware for Fortune 500 enterprise customers.",
    highlights: [
      "Massive learning portal with free cloud certifications and bootcamps",
      "Broad exposure across diverse global industries",
    ],
    applyUrl: "https://careers.cognizant.com/global/en",
    demoUrl: "/demo-application",
  },

  // --- Indian Growth Startups & High-Potential Scale-Ups ---
  {
    id: "job-sarv-in-41",
    title: "AI Research & Generative Systems Engineer",
    company: "Sarvam AI",
    logoColor: "bg-indigo-600",
    roleCategory: "AI / ML Engineer",
    location: "Bengaluru, India",
    workplaceType: "Onsite",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "₹20,00,000 - ₹35,00,000 / yr",
    salaryMin: 120000,
    salaryMax: 180000,
    postedDaysAgo: 1,
    requiredSkills: ["Python", "PyTorch", "LLM", "Prompt Engineering", "CUDA", "FastAPI"],
    preferredSkills: ["Indic Languages", "vLLM", "Distributed Training", "LangChain", "Docker"],
    description: "Build sovereign foundational AI models, Indic language tokenizers, and voice agents tailored for 1.4 billion Indians at Sarvam AI.",
    highlights: [
      "India's premier generative AI foundation model startup backed by Lightspeed & Peak XV",
      "Work directly at the frontier of population-scale AI research and inference",
    ],
    applyUrl: "https://jobs.ashbyhq.com/sarvam",
    demoUrl: "/demo-application",
  },
  {
    id: "job-sign-in-42",
    title: "Full Stack Observability Platform Engineer",
    company: "SigNoz",
    logoColor: "bg-blue-600",
    roleCategory: "Full Stack Engineer",
    location: "Bengaluru, India / Remote (India)",
    workplaceType: "Remote",
    experienceLevel: "Mid-Level",
    salaryRange: "₹18,00,000 - ₹30,00,000 / yr",
    salaryMin: 110000,
    salaryMax: 160000,
    postedDaysAgo: 1,
    requiredSkills: ["Go", "React", "TypeScript", "ClickHouse", "OpenTelemetry", "Docker"],
    preferredSkills: ["Kubernetes", "Kafka", "Prometheus", "Distributed Tracing", "Next.js"],
    description: "Build open-source application performance monitoring (APM), distributed tracing, and metrics indexing used by thousands of engineering teams globally.",
    highlights: [
      "Top open-source developer tooling startup backed by Y Combinator",
      "100% remote-first culture with transparent compensation and equity",
    ],
    applyUrl: "https://jobs.ashbyhq.com/signoz",
    demoUrl: "/demo-application",
  },
  {
    id: "job-port-in-43",
    title: "Backend Engineer - Intra-City Logistics & Fleet Routing",
    company: "Porter",
    logoColor: "bg-blue-600",
    roleCategory: "Backend Engineer",
    location: "Bengaluru / Mumbai, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹15,00,000 - ₹25,00,000 / yr",
    salaryMin: 100000,
    salaryMax: 150000,
    postedDaysAgo: 2,
    requiredSkills: ["Java", "Go", "MySQL", "Redis", "Kafka", "Microservices"],
    preferredSkills: ["Location Algorithms", "AWS", "Docker", "Kubernetes", "PostgreSQL"],
    description: "Design real-time driver allocation, dynamic surge pricing, and multi-stop delivery route optimization handling millions of trips monthly.",
    highlights: [
      "Fast-growing unicorn powering intra-city commercial logistics in 20+ cities",
      "Strong engineering mentorship and generous ESOP programs",
    ],
    applyUrl: "https://jobs.lever.co/porter",
    demoUrl: "/demo-application",
  },
  {
    id: "job-hrk-in-44",
    title: "Frontend Platform Engineer - Developer Code Sandbox",
    company: "HackerRank",
    logoColor: "bg-emerald-700",
    roleCategory: "Frontend Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "₹16,00,000 - ₹28,00,000 / yr",
    salaryMin: 110000,
    salaryMax: 160000,
    postedDaysAgo: 2,
    requiredSkills: ["React", "TypeScript", "JavaScript", "HTML5", "CSS", "WebSockets"],
    preferredSkills: ["Monaco Editor", "Web Workers", "Next.js", "Redux", "Jest"],
    description: "Build interactive browser code editors, live pair-programming workspaces, and developer skills assessment suites for 30M+ engineers.",
    highlights: [
      "Shape the future of technical hiring and developer evaluation",
      "Flexible hybrid working in Bengaluru Koramangala tech hub",
    ],
    applyUrl: "https://job-boards.greenhouse.io/hackerrank",
    demoUrl: "/demo-application",
  },
  {
    id: "job-ship-in-45",
    title: "Backend Engineer - E-Commerce Logistics Aggregator",
    company: "Shiprocket",
    logoColor: "bg-purple-700",
    roleCategory: "Backend Engineer",
    location: "Gurgaon / Delhi NCR, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹12,00,000 - ₹22,00,000 / yr",
    salaryMin: 90000,
    salaryMax: 140000,
    postedDaysAgo: 2,
    requiredSkills: ["PHP", "Python", "Node.js", "MySQL", "Redis", "REST API"],
    preferredSkills: ["AWS", "Kafka", "Docker", "Elasticsearch", "Microservices"],
    description: "Build unified courier integration APIs, live package tracking pipelines, and automated shipping workflows for over 100,000 D2C merchants.",
    highlights: [
      "India's leading D2C shipping unicorn with massive transaction scale",
      "Vibrant Delhi NCR tech environment with high product impact",
    ],
    applyUrl: "https://www.shiprocket.in/careers/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-clr-in-46",
    title: "Full Stack Engineer - Tax & Financial Invoicing APIs",
    company: "Clear (ClearTax)",
    logoColor: "bg-blue-600",
    roleCategory: "Full Stack Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹14,00,000 - ₹24,00,000 / yr",
    salaryMin: 100000,
    salaryMax: 150000,
    postedDaysAgo: 1,
    requiredSkills: ["Java", "React", "TypeScript", "PostgreSQL", "Kafka", "REST API"],
    preferredSkills: ["Docker", "AWS", "Spring Boot", "Next.js", "Microservices"],
    description: "Develop seamless GST e-invoicing platforms, automated tax filing engines, and enterprise financial data pipelines processing billions in invoices.",
    highlights: [
      "Backed by Y Combinator, Founders Fund, and Sequoia",
      "Prime Bengaluru office with excellent engineering perks",
    ],
    applyUrl: "https://cleartax.in/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-khat-in-47",
    title: "Android / Backend Software Engineer - MSME Ledger",
    company: "Khatabook",
    logoColor: "bg-red-600",
    roleCategory: "Full Stack Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹13,00,000 - ₹22,00,000 / yr",
    salaryMin: 90000,
    salaryMax: 140000,
    postedDaysAgo: 3,
    requiredSkills: ["Kotlin", "Node.js", "PostgreSQL", "Redis", "REST API", "Android"],
    preferredSkills: ["Offline-first Architecture", "AWS", "Docker", "TypeScript"],
    description: "Build offline-first digital ledger applications and business management utilities empowering 10M+ Indian small business owners.",
    highlights: [
      "High impact on grassroots digitization of Indian micro-enterprises",
      "Generous health coverage and annual team offsites",
    ],
    applyUrl: "https://khatabook.com/careers/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-pw-in-48",
    title: "EdTech Platform & Live Video Streaming Engineer",
    company: "PhysicsWallah",
    logoColor: "bg-slate-900",
    roleCategory: "Full Stack Engineer",
    location: "Noida / Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹8,00,000 - ₹15,00,000 / yr",
    salaryMin: 70000,
    salaryMax: 120000,
    postedDaysAgo: 2,
    requiredSkills: ["Node.js", "React", "MongoDB", "WebSockets", "WebRTC", "AWS"],
    preferredSkills: ["FFmpeg", "HLS Streaming", "Redis", "Kafka", "Next.js"],
    description: "Engineer ultra-low bandwidth live classroom video streaming, interactive quiz modules, and student mobile apps reaching millions of Indian learners.",
    highlights: [
      "India's most loved and profitable EdTech unicorn",
      "Fast-growing engineering division in Noida and Bengaluru",
    ],
    applyUrl: "https://www.pw.live/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-lens-in-49",
    title: "Computer Vision & Frontend AR Engineer",
    company: "Lenskart",
    logoColor: "bg-teal-700",
    roleCategory: "Frontend Engineer",
    location: "Faridabad / Gurgaon / Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹12,00,000 - ₹22,00,000 / yr",
    salaryMin: 90000,
    salaryMax: 140000,
    postedDaysAgo: 1,
    requiredSkills: ["React", "TypeScript", "WebGL", "Three.js", "HTML5", "CSS"],
    preferredSkills: ["Computer Vision", "TensorFlow.js", "Next.js", "REST API"],
    description: "Build 3D eyewear virtual try-on engines, facial landmark tracking, and lightning-fast omnichannel checkout experiences for Lenskart.",
    highlights: [
      "Direct consumer tech impact across India, SE Asia, and the Middle East",
      "Dynamic product teams with state-of-the-art tech stacks",
    ],
    applyUrl: "https://www.lenskart.com/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-ath-in-50",
    title: "Embedded Linux & Vehicle UI Software Engineer",
    company: "Ather Energy",
    logoColor: "bg-emerald-600",
    roleCategory: "Full Stack Engineer",
    location: "Bengaluru, India",
    workplaceType: "Onsite",
    experienceLevel: "Mid-Level",
    salaryRange: "₹12,00,000 - ₹22,00,000 / yr",
    salaryMin: 90000,
    salaryMax: 140000,
    postedDaysAgo: 2,
    requiredSkills: ["C++", "Python", "Qt", "Linux", "Android / AOSP", "Git"],
    preferredSkills: ["CAN Bus", "IoT Telemetry", "Bluetooth BLE", "React Native"],
    description: "Develop the AtherStack smart vehicle operating system, digital touchscreen instrument clusters, and connected EV navigation dashboards.",
    highlights: [
      "India's premier intelligent electric scooter manufacturer",
      "State-of-the-art vehicle R&D and testing facilities in Bengaluru",
    ],
    applyUrl: "https://www.atherenergy.com/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-rap-in-51",
    title: "SDE II - Real-Time Ride Dispatch & High Concurrency",
    company: "Rapido",
    logoColor: "bg-amber-500",
    roleCategory: "Backend Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹16,00,000 - ₹27,00,000 / yr",
    salaryMin: 110000,
    salaryMax: 160000,
    postedDaysAgo: 2,
    requiredSkills: ["Go", "Java", "Redis", "Kafka", "PostgreSQL", "Microservices"],
    preferredSkills: ["Geo-Hashing", "Spatial Algorithms", "AWS", "Kubernetes", "gRPC"],
    description: "Scale high-frequency ride matching, captain geo-tracking, and instant fare calculation processing millions of daily bike & auto rides.",
    highlights: [
      "India's largest bike taxi and auto ride-hailing network",
      "Fast-paced startup culture with generous equity compensation",
    ],
    applyUrl: "https://rapido.bike/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-acko-in-52",
    title: "Software Development Engineer - Instant Claims Engine",
    company: "Acko",
    logoColor: "bg-purple-700",
    roleCategory: "Backend Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹15,00,000 - ₹26,00,000 / yr",
    salaryMin: 100000,
    salaryMax: 155000,
    postedDaysAgo: 2,
    requiredSkills: ["Java", "Go", "PostgreSQL", "Kafka", "Redis", "AWS"],
    preferredSkills: ["Docker", "Kubernetes", "Spring Boot", "FastAPI", "Microservices"],
    description: "Build instant paperless insurance claims processing, dynamic auto underwriting risk engines, and partner integration SDKs.",
    highlights: [
      "India's first digital-native general insurance unicorn",
      "Great work-life balance and comprehensive family medical insurance",
    ],
    applyUrl: "https://www.acko.com/careers/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-darw-in-53",
    title: "Enterprise Backend Engineer - HR Tech Platform",
    company: "Darwinbox",
    logoColor: "bg-pink-600",
    roleCategory: "Backend Engineer",
    location: "Hyderabad, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹12,00,000 - ₹22,00,000 / yr",
    salaryMin: 90000,
    salaryMax: 140000,
    postedDaysAgo: 3,
    requiredSkills: ["Node.js", "Java", "MongoDB", "MySQL", "Redis", "REST API"],
    preferredSkills: ["Microservices", "Docker", "AWS", "Elasticsearch", "React"],
    description: "Scale Asia's fastest-growing enterprise Human Capital Management platform serving over 850+ enterprises and 2M+ employees worldwide.",
    highlights: [
      "Hyderabad-born enterprise SaaS unicorn backed by Salesforce Ventures & Peak XV",
      "Dynamic product teams with structured engineering growth tracks",
    ],
    applyUrl: "https://darwinbox.com/careers.php",
    demoUrl: "/demo-application",
  },
  {
    id: "job-appsm-in-54",
    title: "Full Stack Platform Engineer - Open Source Developer IDE",
    company: "Appsmith",
    logoColor: "bg-orange-600",
    roleCategory: "Full Stack Engineer",
    location: "Bengaluru, India / Remote (India)",
    workplaceType: "Remote",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "₹16,00,000 - ₹28,00,000 / yr",
    salaryMin: 110000,
    salaryMax: 160000,
    postedDaysAgo: 1,
    requiredSkills: ["Java", "TypeScript", "React", "PostgreSQL", "MongoDB", "Docker"],
    preferredSkills: ["Spring WebFlux", "Reactive Programming", "Kubernetes", "Next.js"],
    description: "Build the leading open-source internal tool development framework used by hundreds of thousands of developers globally.",
    highlights: [
      "Top-tier open-source developer tool with 30k+ GitHub stars",
      "100% remote-first policy with generous home office allowances",
    ],
    applyUrl: "https://www.appsmith.com/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-shad-in-55",
    title: "Backend Platform Engineer - Hyperlocal Logistics",
    company: "Shadowfax",
    logoColor: "bg-blue-800",
    roleCategory: "Backend Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹11,00,000 - ₹19,00,000 / yr",
    salaryMin: 80000,
    salaryMax: 130000,
    postedDaysAgo: 2,
    requiredSkills: ["Java", "Python", "MySQL", "Redis", "Kafka", "REST API"],
    preferredSkills: ["AWS", "Docker", "Microservices", "Elasticsearch", "Spatial Indexing"],
    description: "Architect sub-minute delivery dispatch, rider gamification, and e-commerce express delivery routing across 2,500+ Indian pin codes.",
    highlights: [
      "Fast-growing logistics scale-up operating at massive national throughput",
      "High ownership engineering team in HSR Layout, Bengaluru",
    ],
    applyUrl: "https://www.shadowfax.in/careers",
    demoUrl: "/demo-application",
  },

  // --- UK & Europe Tech Opportunities ---
  {
    id: "job-dm-uk-22",
    title: "Research Software Engineer - Frontier Models",
    company: "Google DeepMind",
    logoColor: "bg-blue-800",
    roleCategory: "AI / ML Engineer",
    location: "London, United Kingdom",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "£140,000 - £210,000 / yr",
    salaryMin: 185000,
    salaryMax: 270000,
    postedDaysAgo: 2,
    requiredSkills: ["Python", "C++", "PyTorch", "JAX", "Distributed Training", "LLM"],
    preferredSkills: ["CUDA", "Reinforcement Learning", "Transformers", "Linux"],
    description: "Build cutting-edge distributed training harnesses, model evaluation environments, and agentic workflows alongside world-class AI researchers.",
    highlights: [
      "Work at the absolute forefront of artificial general intelligence",
      "Prime King's Cross London research campus with top-tier benefits",
    ],
    applyUrl: "https://deepmind.google/careers/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-rev-uk-23",
    title: "Senior Frontend Engineer, Global Banking",
    company: "Revolut",
    logoColor: "bg-slate-900",
    roleCategory: "Frontend Engineer",
    location: "London, UK / Remote (Europe)",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "£105,000 - £155,000 / yr",
    salaryMin: 155000,
    salaryMax: 215000,
    postedDaysAgo: 3,
    requiredSkills: ["React", "TypeScript", "JavaScript", "HTML5", "CSS", "Performance Profiling"],
    preferredSkills: ["Next.js", "Redux Toolkit", "Design Systems", "Jest", "GraphQL"],
    description: "Engineer high-security, lightning-fast financial user experiences and web applications serving over 40 million global customers.",
    highlights: [
      "Flexible remote working options across the UK and Europe",
      "High impact role in one of Europe's most valuable fintech scale-ups",
    ],
    applyUrl: "https://www.revolut.com/careers/position/senior-frontend-engineer-london",
    demoUrl: "/demo-application",
  },
];
