/**
 * Curated Tech Market Job Directory
 * Represents rich, real-world tech job opportunities across AI/ML, Full Stack,
 * Frontend, Backend, Cloud/DevOps, and Data Engineering.
 */

export const JOB_DIRECTORY = [
  // --- AI / ML Engineering ---
  {
    id: "job-oai-01",
    title: "AI Applied Research Engineer",
    company: "OpenAI",
    logoColor: "bg-emerald-700",
    roleCategory: "AI / ML Engineer",
    location: "San Francisco, CA",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "$195,000 - $280,000",
    salaryMin: 195000,
    salaryMax: 280000,
    postedDaysAgo: 1,
    requiredSkills: ["Python", "PyTorch", "LLM", "Prompt Engineering", "API Design", "TypeScript"],
    preferredSkills: ["RLHF", "LangChain", "Vector Databases", "Distributed Training", "Next.js"],
    description: "Join OpenAI's applied engineering team to build developer-facing APIs, fine-tuning infrastructure, and agent workflows powering next-generation generative AI products.",
    highlights: [
      "Work directly with GPT frontier models and inference optimization",
      "Scale developer tooling handling billions of token requests daily",
      "Competitive equity package + full healthcare + 401(k) matching",
    ],
    applyUrl: "https://job-boards.greenhouse.io/openai/jobs/5277884004",
    demoUrl: "/demo-application",
  },
  {
    id: "job-ant-02",
    title: "Full Stack AI Engineer",
    company: "Anthropic",
    logoColor: "bg-amber-700",
    roleCategory: "AI / ML Engineer",
    location: "San Francisco, CA / Remote (US)",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "$210,000 - $310,000",
    salaryMin: 210000,
    salaryMax: 310000,
    postedDaysAgo: 2,
    requiredSkills: ["TypeScript", "React", "Python", "Next.js", "Claude API", "TailwindCSS"],
    preferredSkills: ["FastAPI", "PostgreSQL", "Prompt Caching", "Docker", "AWS"],
    description: "Build interactive user experiences, web tooling, and evaluation harnesses around Claude 3.5 Sonnet and future frontier models with high reliability and safety standards.",
    highlights: [
      "Shape how millions of developers and enterprise users interact with Claude",
      "Autonomous product ownership with rapid release cycles",
      "Comprehensive remote stipend and top-tier benefits",
    ],
    applyUrl: "https://job-boards.greenhouse.io/anthropic/jobs/4019445007",
    demoUrl: "/demo-application",
  },
  {
    id: "job-sca-03",
    title: "Machine Learning Platform Engineer",
    company: "Scale AI",
    logoColor: "bg-purple-700",
    roleCategory: "AI / ML Engineer",
    location: "New York, NY",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "$165,000 - $225,000",
    salaryMin: 165000,
    salaryMax: 225000,
    postedDaysAgo: 3,
    requiredSkills: ["Python", "Kubernetes", "Docker", "PostgreSQL", "MLOps", "FastAPI"],
    preferredSkills: ["Ray", "PyTorch", "Redis", "Kafka", "GCP"],
    description: "Build robust distributed data ingestion pipelines, model fine-tuning jobs, and reinforcement learning evaluation infrastructure at Scale AI.",
    highlights: [
      "Power training data infrastructure for premier frontier AI labs",
      "Work on high-throughput distributed systems in production",
    ],
    applyUrl: "https://job-boards.greenhouse.io/scaleai/jobs/4329241004",
    demoUrl: "/demo-application",
  },
  {
    id: "job-per-04",
    title: "AI Systems & Inference Engineer",
    company: "Perplexity AI",
    logoColor: "bg-teal-700",
    roleCategory: "AI / ML Engineer",
    location: "San Francisco, CA / Remote",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "$190,000 - $270,000",
    salaryMin: 190000,
    salaryMax: 270000,
    postedDaysAgo: 2,
    requiredSkills: ["Python", "C++", "CUDA", "TensorRT", "FastAPI", "Vector Search"],
    preferredSkills: ["Triton", "PyTorch", "vLLM", "Distributed Systems"],
    description: "Help scale Perplexity's conversational search engine by optimizing real-time search indexing, embeddings retrieval, and low-latency LLM inference.",
    highlights: [
      "Direct impact on millions of daily active search queries",
      "Work with bleeding edge LLM serving engines and custom CUDA kernels",
    ],
    applyUrl: "https://jobs.ashbyhq.com/perplexity/48e91404-5853-4f51-b847-bb7cb1d76378",
    demoUrl: "/demo-application",
  },

  // --- Full Stack Engineering ---
  {
    id: "job-str-05",
    title: "Senior Full Stack Engineer, Developer Platform",
    company: "Stripe",
    logoColor: "bg-indigo-600",
    roleCategory: "Full Stack Engineer",
    location: "Remote (US/Canada)",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "$185,000 - $265,000",
    salaryMin: 185000,
    salaryMax: 265000,
    postedDaysAgo: 1,
    requiredSkills: ["JavaScript", "TypeScript", "React", "Node.js", "API Design", "PostgreSQL"],
    preferredSkills: ["Ruby", "GraphQL", "Microservices", "Next.js", "Redis"],
    description: "Build developer surfaces, dashboard experiences, and scalable APIs that process millions of transactions across the globe for Stripe's payments infrastructure.",
    highlights: [
      "Industry gold standard engineering culture and tooling",
      "100% remote-first team with flexible working hours",
      "Exceptional equity grants and annual performance bonuses",
    ],
    applyUrl: "https://job-boards.greenhouse.io/stripe/jobs/5829103002",
    demoUrl: "/demo-application",
  },
  {
    id: "job-lin-06",
    title: "Product Engineer (Full Stack)",
    company: "Linear",
    logoColor: "bg-blue-600",
    roleCategory: "Full Stack Engineer",
    location: "Remote (Global)",
    workplaceType: "Remote",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "$170,000 - $240,000",
    salaryMin: 170000,
    salaryMax: 240000,
    postedDaysAgo: 3,
    requiredSkills: ["TypeScript", "React", "Node.js", "WebSockets", "CSS", "UI/UX Design"],
    preferredSkills: ["PostgreSQL", "IndexedDB", "GraphQL", "TailwindCSS", "Performance Optimization"],
    description: "Craft high-performance, keyboard-first issue tracking software loved by top engineering organizations worldwide. Heavy emphasis on UI smoothness and snappy state sync.",
    highlights: [
      "World-class product design and ultra-fast client sync architecture",
      "Work with zero bureaucracy in a tight-knit high-talent crew",
      "Top-of-market base salary + equity",
    ],
    applyUrl: "https://jobs.ashbyhq.com/linear/1ccbe0ae-ba8d-4eb4-b976-59bfe00cbe90",
    demoUrl: "/demo-application",
  },
  {
    id: "job-ver-07",
    title: "Full Stack Engineer, Next.js & Cloud",
    company: "Vercel",
    logoColor: "bg-slate-900",
    roleCategory: "Full Stack Engineer",
    location: "Remote",
    workplaceType: "Remote",
    experienceLevel: "Mid-Level",
    salaryRange: "$160,000 - $220,000",
    salaryMin: 160000,
    salaryMax: 220000,
    postedDaysAgo: 4,
    requiredSkills: ["Next.js", "React", "TypeScript", "Node.js", "Server Components", "TailwindCSS"],
    preferredSkills: ["Edge Functions", "Turbopack", "PostgreSQL", "Vercel AI SDK", "Docker"],
    description: "Help build the web platform used by millions of developers. Work on Next.js runtime integration, server action ergonomics, and Vercel dashboard features.",
    highlights: [
      "Direct influence over modern web development standards",
      "Generous equipment and wellness stipend",
    ],
    applyUrl: "https://job-boards.greenhouse.io/vercel/jobs/5645391",
    demoUrl: "/demo-application",
  },
  {
    id: "job-sup-08",
    title: "Full Stack Platform Engineer",
    company: "Supabase",
    logoColor: "bg-emerald-600",
    roleCategory: "Full Stack Engineer",
    location: "Remote (Global)",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "$165,000 - $230,000",
    salaryMin: 165000,
    salaryMax: 230000,
    postedDaysAgo: 5,
    requiredSkills: ["TypeScript", "React", "PostgreSQL", "Node.js", "Docker", "REST API"],
    preferredSkills: ["Go", "Elixir", "Supabase Auth", "Next.js", "GraphQL"],
    description: "Build open source cloud tooling for developers. Work on database dashboards, real-time sync, auth integrations, and edge functions management.",
    highlights: [
      "100% remote asynchronous team across 30+ countries",
      "Build open source software used by 1M+ developers",
    ],
    applyUrl: "https://jobs.ashbyhq.com/supabase/305e9112-a5f7-4ebc-8857-7bbfaecb9ae9",
    demoUrl: "/demo-application",
  },

  // --- Frontend Engineer ---
  {
    id: "job-air-09",
    title: "Senior Frontend Engineer, Guest Experiences",
    company: "Airbnb",
    logoColor: "bg-rose-600",
    roleCategory: "Frontend Engineer",
    location: "San Francisco, CA / Remote",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "$175,000 - $250,000",
    salaryMin: 175000,
    salaryMax: 250000,
    postedDaysAgo: 2,
    requiredSkills: ["React", "TypeScript", "HTML5", "CSS", "Design Systems", "Web Performance"],
    preferredSkills: ["Next.js", "Accessibility (a11y)", "GraphQL", "Jest", "TailwindCSS"],
    description: "Design and implement world-class responsive web applications for millions of travelers. Champion accessible design, smooth micro-animations, and fast page loads.",
    highlights: [
      "Live and work anywhere program (travel stipends provided)",
      "Work with one of the most respected design system teams in tech",
    ],
    applyUrl: "https://careers.airbnb.com/positions/5640231/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-ret-10",
    title: "Frontend Systems Engineer",
    company: "Retool",
    logoColor: "bg-sky-600",
    roleCategory: "Frontend Engineer",
    location: "San Francisco, CA / New York, NY",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "$165,000 - $235,000",
    salaryMin: 165000,
    salaryMax: 235000,
    postedDaysAgo: 4,
    requiredSkills: ["TypeScript", "React", "JavaScript", "State Management", "DOM Performance"],
    preferredSkills: ["Canvas", "Web Workers", "Node.js", "PostgreSQL", "Cypress"],
    description: "Build Retool's core drag-and-drop IDE canvas, custom component runtime, and rich layout engine used by Fortune 500 companies to build internal tools.",
    highlights: [
      "Complex client-side architecture solving hard browser performance problems",
      "Fast-growing B2B product with huge developer traction",
    ],
    applyUrl: "https://job-boards.greenhouse.io/retool/jobs/5823194",
    demoUrl: "/demo-application",
  },
  {
    id: "job-fig-11",
    title: "Software Engineer, Web Platform & UI",
    company: "Figma",
    logoColor: "bg-violet-600",
    roleCategory: "Frontend Engineer",
    location: "San Francisco, CA / Remote",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "$180,000 - $260,000",
    salaryMin: 180000,
    salaryMax: 260000,
    postedDaysAgo: 1,
    requiredSkills: ["TypeScript", "React", "WebGL", "CSS", "WebAssembly", "Data Structures"],
    preferredSkills: ["C++", "Rust", "Design Systems", "Performance Profiling"],
    description: "Work on Figma's web application surface, multiplayer real-time collaboration canvas, and developer inspection modes.",
    highlights: [
      "Push browser capabilities to the absolute limit",
      "Unmatched collaborative design culture and strong perks",
    ],
    applyUrl: "https://job-boards.greenhouse.io/figma/jobs/5918231",
    demoUrl: "/demo-application",
  },

  // --- Backend / Distributed Systems ---
  {
    id: "job-ube-12",
    title: "Senior Backend Engineer, Core Logistics",
    company: "Uber",
    logoColor: "bg-black",
    roleCategory: "Backend Engineer",
    location: "Sunnyvale, CA / Seattle, WA",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "$180,000 - $260,000",
    salaryMin: 180000,
    salaryMax: 260000,
    postedDaysAgo: 3,
    requiredSkills: ["Go", "Java", "PostgreSQL", "Kafka", "Microservices", "System Design"],
    preferredSkills: ["Redis", "gRPC", "Docker", "Kubernetes", "Cassandra"],
    description: "Architect high-throughput real-time matching, dispatch, and routing algorithms serving tens of millions of rides and deliveries every single day.",
    highlights: [
      "Petabyte-scale distributed systems and high-availability operations",
      "Generous RSU refreshers and competitive annual bonus",
    ],
    applyUrl: "https://uber.wd5.myworkdayjobs.com/UberCareers/job/Software-Engineer-Backend_JR123456",
    demoUrl: "/demo-application",
  },
  {
    id: "job-cld-13",
    title: "Systems Engineer, Distributed Edge Storage",
    company: "Cloudflare",
    logoColor: "bg-orange-600",
    roleCategory: "Backend Engineer",
    location: "Austin, TX / Remote",
    workplaceType: "Remote",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "$160,000 - $230,000",
    salaryMin: 160000,
    salaryMax: 230000,
    postedDaysAgo: 5,
    requiredSkills: ["Rust", "Go", "Distributed Systems", "Linux", "Networking", "API Design"],
    preferredSkills: ["C++", "PostgreSQL", "Docker", "eBPF", "TypeScript"],
    description: "Design low-latency key-value storage, database replication, and edge computing primitives running across Cloudflare's 300+ city global network.",
    highlights: [
      "Help make the global internet faster and more secure",
      "Strong remote-friendly engineering culture",
    ],
    applyUrl: "https://job-boards.greenhouse.io/cloudflare/jobs/5839210",
    demoUrl: "/demo-application",
  },
  {
    id: "job-dat-14",
    title: "Backend Engineer, Observability Pipelines",
    company: "Datadog",
    logoColor: "bg-purple-800",
    roleCategory: "Backend Engineer",
    location: "New York, NY / Boston, MA",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "$155,000 - $215,000",
    salaryMin: 155000,
    salaryMax: 215000,
    postedDaysAgo: 2,
    requiredSkills: ["Python", "Go", "PostgreSQL", "Kafka", "Docker", "REST API"],
    preferredSkills: ["Kubernetes", "Redis", "Elasticsearch", "AWS", "Prometheus"],
    description: "Build telemetry processing engines that stream trillions of metrics, logs, and traces per day with sub-second query latency.",
    highlights: [
      "Fastest growing cloud observability platform",
      "Work with massive scale distributed databases and streaming pipelines",
    ],
    applyUrl: "https://job-boards.greenhouse.io/datadog/jobs/5719382",
    demoUrl: "/demo-application",
  },

  // --- DevOps / Cloud / Platform ---
  {
    id: "job-aws-15",
    title: "Cloud Infrastructure & Platform Engineer",
    company: "Amazon Web Services (AWS)",
    logoColor: "bg-amber-600",
    roleCategory: "DevOps / Cloud Engineer",
    location: "Seattle, WA / Arlington, VA",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "$170,000 - $250,000",
    salaryMin: 170000,
    salaryMax: 250000,
    postedDaysAgo: 4,
    requiredSkills: ["AWS", "Kubernetes", "Terraform", "Docker", "CI/CD", "Linux"],
    preferredSkills: ["Python", "Go", "Helm", "Prometheus", "Security / IAM"],
    description: "Build self-service container orchestration, multi-region failover, and infrastructure-as-code automation for Tier-1 cloud services.",
    highlights: [
      "Foundational infrastructure supporting the global internet economy",
      "Substantial total compensation and industry prestige",
    ],
    applyUrl: "https://amazon.jobs/en/jobs/2598341/software-development-engineer-aws",
    demoUrl: "/demo-application",
  },
  {
    id: "job-has-16",
    title: "DevOps & SRE Engineer",
    company: "HashiCorp",
    logoColor: "bg-slate-800",
    roleCategory: "DevOps / Cloud Engineer",
    location: "Remote (US/Canada)",
    workplaceType: "Remote",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "$160,000 - $225,000",
    salaryMin: 160000,
    salaryMax: 225000,
    postedDaysAgo: 3,
    requiredSkills: ["Terraform", "Kubernetes", "Go", "Docker", "Linux", "GCP/AWS"],
    preferredSkills: ["Vault", "Consul", "Python", "Observability", "Ansible"],
    description: "Manage and automate multi-cloud infrastructure, internal deployment pipelines, and zero-trust security perimeters using HashiCorp Cloud Platform.",
    highlights: [
      "Pioneer in Infrastructure as Code and cloud automation",
      "True remote-first culture with generous home office allowances",
    ],
    applyUrl: "https://job-boards.greenhouse.io/hashicorp/jobs/5632190",
    demoUrl: "/demo-application",
  },

  // --- Data Engineering / Analytics ---
  {
    id: "job-sno-17",
    title: "Senior Data Platform Engineer",
    company: "Snowflake",
    logoColor: "bg-cyan-600",
    roleCategory: "Data Engineer",
    location: "San Mateo, CA / Remote",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "$180,000 - $255,000",
    salaryMin: 180000,
    salaryMax: 255000,
    postedDaysAgo: 2,
    requiredSkills: ["SQL", "Python", "Snowflake", "Data Warehousing", "ETL", "Kafka"],
    preferredSkills: ["Spark", "dbt", "Airflow", "Docker", "AWS"],
    description: "Architect petabyte-scale data pipelines, real-time analytics streaming, and enterprise data governance infrastructure for Snowflake's cloud platform.",
    highlights: [
      "Work at the cutting edge of cloud data warehousing and data science",
      "Highly competitive compensation and RSU packages",
    ],
    applyUrl: "https://job-boards.greenhouse.io/snowflake/jobs/5812903",
    demoUrl: "/demo-application",
  },
  {
    id: "job-dbt-18",
    title: "Analytics & Data Integration Engineer",
    company: "dbt Labs",
    logoColor: "bg-orange-500",
    roleCategory: "Data Engineer",
    location: "Remote",
    workplaceType: "Remote",
    experienceLevel: "Mid-Level",
    salaryRange: "$150,000 - $205,000",
    salaryMin: 150000,
    salaryMax: 205000,
    postedDaysAgo: 6,
    requiredSkills: ["SQL", "Python", "dbt", "PostgreSQL", "Data Modeling", "Git"],
    preferredSkills: ["BigQuery", "Snowflake", "Airflow", "TypeScript", "CI/CD"],
    description: "Empower thousands of data teams to transform data in production. Build dbt Cloud plugins, semantic layer models, and data testing automations.",
    highlights: [
      "Creator of the open source standard for modern data transformation",
      "Transparent remote company culture and strong community",
    ],
    applyUrl: "https://job-boards.greenhouse.io/dbtlabsinc/jobs/5891234",
    demoUrl: "/demo-application",
  },

  // --- India Tech Opportunities ---
  {
    id: "job-atl-in-19",
    title: "Senior Full Stack Software Engineer",
    company: "Atlassian",
    logoColor: "bg-blue-700",
    roleCategory: "Full Stack Engineer",
    location: "Bengaluru, India / Remote (India)",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "₹38,00,000 - ₹55,00,000 / yr",
    salaryMin: 180000,
    salaryMax: 250000,
    postedDaysAgo: 1,
    requiredSkills: ["React", "TypeScript", "Node.js", "Java", "Microservices", "REST API"],
    preferredSkills: ["GraphQL", "AWS", "PostgreSQL", "Kafka", "Docker"],
    description: "Join Atlassian's core Jira and Confluence cloud engineering group in India. Build scalable micro-frontend architectures and distributed cloud microservices.",
    highlights: [
      "TEAM Anywhere policy: 100% remote working flexibility across India",
      "World-class R&D campus in Bengaluru with extensive learning benefits",
    ],
    applyUrl: "https://www.atlassian.com/company/careers/details/R-00000438",
    demoUrl: "/demo-application",
  },
  {
    id: "job-goog-in-20",
    title: "Senior Software Engineer - Google Cloud & Search Infra",
    company: "Google",
    logoColor: "bg-blue-600",
    roleCategory: "Backend Engineer",
    location: "Bengaluru / Hyderabad, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹48,00,000 - ₹72,00,000 / yr",
    salaryMin: 190000,
    salaryMax: 290000,
    postedDaysAgo: 1,
    requiredSkills: ["C++", "Java", "Go", "Distributed Systems", "Kubernetes", "gRPC"],
    preferredSkills: ["Borg", "Spanner", "Bigtable", "Linux Kernel", "Machine Learning"],
    description: "Build global-scale infrastructure, cloud storage engines, and search indexing systems supporting billions of queries daily at Google India R&D centers.",
    highlights: [
      "Work on critical distributed systems powering Google Cloud & Global Search",
      "Comprehensive healthcare, annual equity refreshers, and hybrid flexibility",
    ],
    applyUrl: "https://www.google.com/about/careers/applications/jobs/results/?location=India",
    demoUrl: "/demo-application",
  },
  {
    id: "job-msft-in-21",
    title: "Software Engineer II - Azure AI Platform",
    company: "Microsoft",
    logoColor: "bg-blue-600",
    roleCategory: "AI / ML Engineer",
    location: "Hyderabad / Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryRange: "₹32,00,000 - ₹48,00,000 / yr",
    salaryMin: 160000,
    salaryMax: 220000,
    postedDaysAgo: 2,
    requiredSkills: ["Python", "C#", "PyTorch", "Azure", "Distributed Systems", "REST API"],
    preferredSkills: ["LLM", "Docker", "Kubernetes", "C++", "FastAPI"],
    description: "Develop generative AI inference engines, model fine-tuning frameworks, and enterprise Copilot integration platforms at Microsoft IDC India.",
    highlights: [
      "Work directly on OpenAI integration and Azure AI infrastructure",
      "Comprehensive family health insurance and annual stock refreshers",
    ],
    applyUrl: "https://jobs.careers.microsoft.com/global/en/job/1769824",
    demoUrl: "/demo-application",
  },
  {
    id: "job-amzn-in-22",
    title: "Software Development Engineer II (SDE II) - AWS Infrastructure",
    company: "Amazon",
    logoColor: "bg-amber-600",
    roleCategory: "Backend Engineer",
    location: "Bengaluru / Hyderabad, India",
    workplaceType: "Hybrid",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "₹36,00,000 - ₹54,00,000 / yr",
    salaryMin: 170000,
    salaryMax: 240000,
    postedDaysAgo: 2,
    requiredSkills: ["Java", "Distributed Systems", "AWS", "DynamoDB", "REST API", "CI/CD"],
    preferredSkills: ["Kotlin", "Lambda", "Docker", "Microservices", "Event-Driven Architecture"],
    description: "Architect high-availability AWS cloud control planes and retail high-throughput microservices handling millions of transactions per minute.",
    highlights: [
      "Direct ownership of tier-1 cloud services running at global hyper-scale",
      "Robust stock grant package and structured engineering growth tracks",
    ],
    applyUrl: "https://amazon.jobs/en/search?loc_query=India",
    demoUrl: "/demo-application",
  },
  {
    id: "job-flip-in-23",
    title: "Lead Software Engineer - Supply Chain & Logistics Tech",
    company: "Flipkart",
    logoColor: "bg-blue-600",
    roleCategory: "Backend Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹45,00,000 - ₹68,00,000 / yr",
    salaryMin: 180000,
    salaryMax: 260000,
    postedDaysAgo: 1,
    requiredSkills: ["Java", "Kafka", "MySQL", "Redis", "Distributed Systems", "Microservices"],
    preferredSkills: ["HBase", "Aerospike", "Spring Boot", "Docker", "Kubernetes"],
    description: "Lead architecture and engineering for Flipkart's core fulfilment and real-time inventory management engines powering India's largest e-commerce festivals.",
    highlights: [
      "Design systems capable of scaling to 100k+ requests per second during Big Billion Days",
      "Generous performance bonuses and Flipkart stock ownership programs",
    ],
    applyUrl: "https://www.flipkartcareers.com/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-swig-in-24",
    title: "Backend Platform Engineer, High Scale Logistics",
    company: "Swiggy",
    logoColor: "bg-orange-600",
    roleCategory: "Backend Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹40,00,000 - ₹60,00,000 / yr",
    salaryMin: 170000,
    salaryMax: 240000,
    postedDaysAgo: 3,
    requiredSkills: ["Go", "Java", "Kafka", "Redis", "PostgreSQL", "Distributed Systems"],
    preferredSkills: ["Kubernetes", "AWS", "gRPC", "Elasticsearch", "Cassandra"],
    description: "Architect high-throughput, low-latency dispatch and routing algorithms handling millions of daily on-demand delivery orders.",
    highlights: [
      "Ultra high-scale distributed architecture processing peak Indian traffic",
      "Fast-paced product engineering environment with generous equity",
    ],
    applyUrl: "https://careers.swiggy.com/#/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-rzp-in-25",
    title: "Staff Platform Engineer - Payment Gateway Core",
    company: "Razorpay",
    logoColor: "bg-blue-700",
    roleCategory: "Backend Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹50,00,000 - ₹75,00,000 / yr",
    salaryMin: 190000,
    salaryMax: 280000,
    postedDaysAgo: 1,
    requiredSkills: ["Go", "Node.js", "PostgreSQL", "Kafka", "Redis", "Microservices"],
    preferredSkills: ["AWS", "Docker", "Kubernetes", "Fintech API", "High Concurrency"],
    description: "Build ultra-reliable payment processing engines and instant settlement infrastructure handling over $100B+ annual total payment volume.",
    highlights: [
      "Direct impact on powering digital payments for 10M+ Indian businesses",
      "Top-tier fintech compensation with ESOP liquidity programs",
    ],
    applyUrl: "https://razorpay.com/jobs/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-php-in-26",
    title: "Senior Software Engineer - UPI Core & Merchant Platform",
    company: "PhonePe",
    logoColor: "bg-purple-700",
    roleCategory: "Backend Engineer",
    location: "Bengaluru / Pune, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹42,00,000 - ₹65,00,000 / yr",
    salaryMin: 175000,
    salaryMax: 250000,
    postedDaysAgo: 2,
    requiredSkills: ["Java", "Spring Boot", "Kafka", "HBase", "MySQL", "Distributed Caching"],
    preferredSkills: ["Aerospike", "Kubernetes", "gRPC", "Microservices", "Observability"],
    description: "Power India's largest UPI payments network processing over 45% of total national UPI volume with 99.999% uptime guarantees.",
    highlights: [
      "Architect sub-millisecond payment settlement pipelines at nationwide scale",
      "Generous stock options and comprehensive employee wellness perks",
    ],
    applyUrl: "https://www.phonepe.com/careers/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-crd-in-27",
    title: "Senior Backend / Systems Engineer - Financial Ledger",
    company: "CRED",
    logoColor: "bg-slate-900",
    roleCategory: "Backend Engineer",
    location: "Bengaluru, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹45,00,000 - ₹70,00,000 / yr",
    salaryMin: 180000,
    salaryMax: 270000,
    postedDaysAgo: 2,
    requiredSkills: ["Go", "Java", "PostgreSQL", "Kafka", "Redis", "Distributed Systems"],
    preferredSkills: ["Event Sourcing", "Docker", "Kubernetes", "AWS", "Financial Engines"],
    description: "Engineer immutable double-entry ledger platforms and high-speed reward verification engines for India's premier creditworthy community.",
    highlights: [
      "Work alongside world-class engineering talent with craft-first design culture",
      "Industry-leading equity packages and comprehensive family insurance",
    ],
    applyUrl: "https://jobs.lever.co/cred",
    demoUrl: "/demo-application",
  },
  {
    id: "job-post-in-28",
    title: "Senior Full Stack Platform Engineer - API Runtime",
    company: "Postman",
    logoColor: "bg-orange-600",
    roleCategory: "Full Stack Engineer",
    location: "Bengaluru, India / Remote (India)",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "₹38,00,000 - ₹58,00,000 / yr",
    salaryMin: 175000,
    salaryMax: 250000,
    postedDaysAgo: 3,
    requiredSkills: ["TypeScript", "Node.js", "React", "Next.js", "Electron", "REST API"],
    preferredSkills: ["GraphQL", "WebSockets", "Docker", "AWS", "API Specifications"],
    description: "Build features for the world's leading API platform used by over 30 million developers across 500,000 organizations worldwide.",
    highlights: [
      "100% remote working flexibility across India with home office setup stipends",
      "Direct impact on the global developer ecosystem and API standards",
    ],
    applyUrl: "https://www.postman.com/company/careers/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-zept-in-29",
    title: "Lead Backend Engineer - 10-Minute Dark Store Dispatch Engine",
    company: "Zepto",
    logoColor: "bg-purple-800",
    roleCategory: "Backend Engineer",
    location: "Bengaluru / Mumbai, India",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹42,00,000 - ₹65,00,000 / yr",
    salaryMin: 175000,
    salaryMax: 250000,
    postedDaysAgo: 2,
    requiredSkills: ["Go", "Node.js", "PostgreSQL", "Redis", "Kafka", "Microservices"],
    preferredSkills: ["Spatial Indexing", "Kubernetes", "AWS", "Elasticsearch", "FastAPI"],
    description: "Architect sub-second dark store picker routing, hyper-local inventory allocations, and rider batching algorithms for quick-commerce delivery.",
    highlights: [
      "High velocity, hyper-growth quick-commerce engineering environment",
      "Significant pre-IPO equity grants and aggressive career acceleration",
    ],
    applyUrl: "https://www.zeptonow.com/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-zom-in-30",
    title: "Senior Backend Engineer - Live Order Stream & Quick Commerce",
    company: "Zomato",
    logoColor: "bg-red-600",
    roleCategory: "Backend Engineer",
    location: "Gurgaon / Remote (India)",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "₹38,00,000 - ₹58,00,000 / yr",
    salaryMin: 170000,
    salaryMax: 245000,
    postedDaysAgo: 1,
    requiredSkills: ["Go", "Python", "Kafka", "MySQL", "Redis", "Distributed Systems"],
    preferredSkills: ["Kubernetes", "AWS", "gRPC", "Elasticsearch", "ClickHouse"],
    description: "Design live streaming event processing architectures, real-time rider tracking, and merchant catalog sync for millions of food and grocery orders.",
    highlights: [
      "Operate at peak national concurrency handling record festival demand",
      "Dynamic tech culture with high autonomy and attractive equity upside",
    ],
    applyUrl: "https://www.zomato.com/careers",
    demoUrl: "/demo-application",
  },
  {
    id: "job-zero-in-31",
    title: "Systems & Backend Engineer - Kite Ultra-Low Latency Trading",
    company: "Zerodha",
    logoColor: "bg-blue-700",
    roleCategory: "Backend Engineer",
    location: "Bengaluru, India / Remote (India)",
    workplaceType: "Remote",
    experienceLevel: "Mid-to-Senior",
    salaryRange: "₹35,00,000 - ₹55,00,000 / yr",
    salaryMin: 170000,
    salaryMax: 240000,
    postedDaysAgo: 2,
    requiredSkills: ["Go", "Python", "PostgreSQL", "Redis", "Linux", "WebSockets"],
    preferredSkills: ["C", "Rust", "Network Protocols", "Distributed Systems", "Nginx"],
    description: "Build robust, minimalist, ultra-low latency trading systems and market data streaming pipelines handling 15M+ active retail investors.",
    highlights: [
      "Remote-first engineering team renowned for clean, unbloated software craft",
      "Exceptional work-life balance and transparent compensation",
    ],
    applyUrl: "https://zerodha.com/careers",
    demoUrl: "/demo-application",
  },

  // --- UK & Europe Tech Opportunities ---
  {
    id: "job-dm-uk-22",
    title: "Research Software Engineer - Frontier Models",
    company: "Google DeepMind",
    logoColor: "bg-blue-800",
    roleCategory: "AI / ML Engineer",
    location: "London, United Kingdom",
    workplaceType: "Hybrid",
    experienceLevel: "Senior",
    salaryRange: "£140,000 - £210,000 / yr",
    salaryMin: 185000,
    salaryMax: 270000,
    postedDaysAgo: 2,
    requiredSkills: ["Python", "C++", "PyTorch", "JAX", "Distributed Training", "LLM"],
    preferredSkills: ["CUDA", "Reinforcement Learning", "Transformers", "Linux"],
    description: "Build cutting-edge distributed training harnesses, model evaluation environments, and agentic workflows alongside world-class AI researchers.",
    highlights: [
      "Work at the absolute forefront of artificial general intelligence",
      "Prime King's Cross London research campus with top-tier benefits",
    ],
    applyUrl: "https://deepmind.google/careers/",
    demoUrl: "/demo-application",
  },
  {
    id: "job-rev-uk-23",
    title: "Senior Frontend Engineer, Global Banking",
    company: "Revolut",
    logoColor: "bg-slate-900",
    roleCategory: "Frontend Engineer",
    location: "London, UK / Remote (Europe)",
    workplaceType: "Remote",
    experienceLevel: "Senior",
    salaryRange: "£105,000 - £155,000 / yr",
    salaryMin: 155000,
    salaryMax: 215000,
    postedDaysAgo: 3,
    requiredSkills: ["React", "TypeScript", "JavaScript", "HTML5", "CSS", "Performance Profiling"],
    preferredSkills: ["Next.js", "Redux Toolkit", "Design Systems", "Jest", "GraphQL"],
    description: "Engineer high-security, lightning-fast financial user experiences and web applications serving over 40 million global customers.",
    highlights: [
      "Flexible remote working options across the UK and Europe",
      "High impact role in one of Europe's most valuable fintech scale-ups",
    ],
    applyUrl: "https://www.revolut.com/careers/position/senior-frontend-engineer-london",
    demoUrl: "/demo-application",
  },
];
